#ifndef __IRQPRIO_H
#define __IRQPRIO_H

#include "freertos.h"

#define HIGHEST_RTOS_PRIO		configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY
#define I2C1_EV_IRQ_PRIO		HIGHEST_RTOS_PRIO
#define I2C1_ER_IRQ_PRIO		(I2C1_EV_IRQ_PRIO+1)		// lower than I2C1_EV_IRQ_PRIO

#define USART_IRQ_PRIO			(HIGHEST_RTOS_PRIO+1)
#define USART1_IRQ_PRIO			USART_IRQ_PRIO
#define USART2_IRQ_PRIO			USART_IRQ_PRIO
#define USART3_IRQ_PRIO			USART_IRQ_PRIO

#define ETH_IRQ_PRIO			(HIGHEST_RTOS_PRIO+2)		// lowest priority

#define DMA2_Channel1_IRQ_PRIO	(HIGHEST_RTOS_PRIO+3)
#define SPI3_IRQ_PRIO			(HIGHEST_RTOS_PRIO+3)

#define KBD_IRQn_EXTI_IRQ_PRIO	(HIGHEST_RTOS_PRIO+2)

#endif
